
export const students = [
  {
    firstName: "Олексій",
    lastName: "Іваненко",
    course: 1,
    avgScore: 82,
    major: "ІТ",
    hobbies: ["програмування", "шахи"],
    hasDebts: false,
    group: "IT-01",
    startYear: 2026,
  },
  {
    firstName: "Марина",
    lastName: "Петренко",
    course: 2,
    avgScore: 90,
    major: "Дизайн",
    hobbies: ["малювання", "дизайн"],
    hasDebts: false,
    group: "DS-02",
    startYear: 2025,
  },
  {
    firstName: "Петро",
    lastName: "Шевченко",
    course: 3,
    avgScore: 75,
    major: "Економіка",
    hobbies: ["аналітика", "читання"],
    hasDebts: true,
    group: "EC-03",
    startYear: 2024,
  },
  {
    firstName: "Ірина",
    lastName: "Ковальчук",
    course: 4,
    avgScore: 88,
    major: "Право",
    hobbies: ["дебати", "читання"],
    hasDebts: false,
    group: "LW-04",
    startYear: 2023,
  },
  {
    firstName: "Андрій",
    lastName: "Бондар",
    course: 2,
    avgScore: 79,
    major: "Маркетинг",
    hobbies: ["SMM", "блогінг"],
    hasDebts: true,
    group: "MK-05",
    startYear: 2025,
  },

  {
    firstName: "Вікторія",
    lastName: "Ткаченко",
    course: 1,
    avgScore: 91,
    major: "ІТ",
    hobbies: ["геймдев", "спорт"],
    hasDebts: false,
    group: "IT-01",
    startYear: 2026,
  },
  {
    firstName: "Денис",
    lastName: "Кравчук",
    course: 3,
    avgScore: 80,
    major: "ІТ",
    hobbies: ["бекенд", "футбол"],
    hasDebts: false,
    group: "IT-01",
    startYear: 2024,
  },
  {
    firstName: "Оксана",
    lastName: "Мельник",
    course: 2,
    avgScore: 87,
    major: "Дизайн",
    hobbies: ["UX/UI", "малювання"],
    hasDebts: false,
    group: "DS-02",
    startYear: 2025,
  },
  {
    firstName: "Роман",
    lastName: "Шевчук",
    course: 4,
    avgScore: 70,
    major: "Економіка",
    hobbies: ["бізнес", "читання"],
    hasDebts: true,
    group: "EC-03",
    startYear: 2023,
  },
  {
    firstName: "Юлія",
    lastName: "Гриценко",
    course: 1,
    avgScore: 85,
    major: "Право",
    hobbies: ["читання", "шахи"],
    hasDebts: false,
    group: "LW-04",
    startYear: 2026,
  },

  {
    firstName: "Максим",
    lastName: "Романюк",
    course: 2,
    avgScore: 78,
    major: "Маркетинг",
    hobbies: ["реклама", "спорт"],
    hasDebts: true,
    group: "MK-05",
    startYear: 2025,
  },
  {
    firstName: "Аліна",
    lastName: "Савченко",
    course: 3,
    avgScore: 93,
    major: "Дизайн",
    hobbies: ["графіка", "малювання"],
    hasDebts: false,
    group: "DS-02",
    startYear: 2024,
  },
  {
    firstName: "Сергій",
    lastName: "Лисенко",
    course: 4,
    avgScore: 82,
    major: "ІТ",
    hobbies: ["DevOps", "читання"],
    hasDebts: false,
    group: "IT-01",
    startYear: 2023,
  },
  {
    firstName: "Тетяна",
    lastName: "Мороз",
    course: 1,
    avgScore: 89,
    major: "Економіка",
    hobbies: ["фінанси", "аналітика"],
    hasDebts: false,
    group: "EC-03",
    startYear: 2026,
  },
  {
    firstName: "Ігор",
    lastName: "Дяченко",
    course: 2,
    avgScore: 74,
    major: "Право",
    hobbies: ["судові кейси", "читання"],
    hasDebts: true,
    group: "LW-04",
    startYear: 2025,
  },

  {
    firstName: "Наталія",
    lastName: "Іваненко",
    course: 3,
    avgScore: 86,
    major: "Маркетинг",
    hobbies: ["SMM", "блогінг"],
    hasDebts: false,
    group: "MK-05",
    startYear: 2024,
  },
  {
    firstName: "Богдан",
    lastName: "Петренко",
    course: 4,
    avgScore: 77,
    major: "ІТ",
    hobbies: ["програмування", "геймдев"],
    hasDebts: true,
    group: "IT-01",
    startYear: 2023,
  },
  {
    firstName: "Дарина",
    lastName: "Шевченко",
    course: 1,
    avgScore: 92,
    major: "Дизайн",
    hobbies: ["ілюстрація", "дизайн"],
    hasDebts: false,
    group: "DS-02",
    startYear: 2026,
  },
  {
    firstName: "Владислав",
    lastName: "Ковальчук",
    course: 2,
    avgScore: 81,
    major: "Економіка",
    hobbies: ["аналітика", "читання"],
    hasDebts: false,
    group: "EC-03",
    startYear: 2025,
  },
  {
    firstName: "Олена",
    lastName: "Бондар",
    course: 3,
    avgScore: 88,
    major: "Право",
    hobbies: ["дебати", "читання"],
    hasDebts: false,
    group: "LW-04",
    startYear: 2024,
  },

  {
    firstName: "Олексій",
    lastName: "Ткаченко",
    course: 4,
    avgScore: 69,
    major: "Маркетинг",
    hobbies: ["реклама", "спорт"],
    hasDebts: true,
    group: "MK-05",
    startYear: 2023,
  },
  {
    firstName: "Марина",
    lastName: "Кравчук",
    course: 1,
    avgScore: 90,
    major: "ІТ",
    hobbies: ["бекенд", "шахи"],
    hasDebts: false,
    group: "IT-01",
    startYear: 2026,
  },
  {
    firstName: "Петро",
    lastName: "Мельник",
    course: 2,
    avgScore: 76,
    major: "Дизайн",
    hobbies: ["UX/UI", "малювання"],
    hasDebts: true,
    group: "DS-02",
    startYear: 2025,
  },
  {
    firstName: "Ірина",
    lastName: "Шевчук",
    course: 3,
    avgScore: 85,
    major: "Економіка",
    hobbies: ["бізнес", "аналітика"],
    hasDebts: false,
    group: "EC-03",
    startYear: 2024,
  },
  {
    firstName: "Андрій",
    lastName: "Гриценко",
    course: 4,
    avgScore: 83,
    major: "Право",
    hobbies: ["судові кейси", "читання"],
    hasDebts: false,
    group: "LW-04",
    startYear: 2023,
  },

  {
    firstName: "Вікторія",
    lastName: "Романюк",
    course: 1,
    avgScore: 91,
    major: "Маркетинг",
    hobbies: ["SMM", "блогінг"],
    hasDebts: false,
    group: "MK-05",
    startYear: 2026,
  },
  {
    firstName: "Денис",
    lastName: "Савченко",
    course: 2,
    avgScore: 79,
    major: "ІТ",
    hobbies: ["DevOps", "футбол"],
    hasDebts: true,
    group: "IT-01",
    startYear: 2025,
  },
  {
    firstName: "Оксана",
    lastName: "Лисенко",
    course: 3,
    avgScore: 87,
    major: "Дизайн",
    hobbies: ["графіка", "малювання"],
    hasDebts: false,
    group: "DS-02",
    startYear: 2024,
  },
  {
    firstName: "Роман",
    lastName: "Мороз",
    course: 4,
    avgScore: 72,
    major: "Економіка",
    hobbies: ["фінанси", "читання"],
    hasDebts: true,
    group: "EC-03",
    startYear: 2023,
  },
  {
    firstName: "Юлія",
    lastName: "Дяченко",
    course: 1,
    avgScore: 84,
    major: "Право",
    hobbies: ["дебати", "читання"],
    hasDebts: false,
    group: "LW-04",
    startYear: 2026,
  },

  {
    firstName: "Максим",
    lastName: "Іваненко",
    course: 2,
    avgScore: 77,
    major: "Маркетинг",
    hobbies: ["реклама", "спорт"],
    hasDebts: true,
    group: "MK-05",
    startYear: 2025,
  },
  {
    firstName: "Аліна",
    lastName: "Петренко",
    course: 3,
    avgScore: 94,
    major: "ІТ",
    hobbies: ["програмування", "геймдев"],
    hasDebts: false,
    group: "IT-01",
    startYear: 2024,
  },
  {
    firstName: "Сергій",
    lastName: "Шевченко",
    course: 4,
    avgScore: 81,
    major: "Дизайн",
    hobbies: ["UX/UI", "малювання"],
    hasDebts: false,
    group: "DS-02",
    startYear: 2023,
  },
  {
    firstName: "Тетяна",
    lastName: "Ковальчук",
    course: 1,
    avgScore: 88,
    major: "Економіка",
    hobbies: ["аналітика", "читання"],
    hasDebts: false,
    group: "EC-03",
    startYear: 2026,
  },
  {
    firstName: "Ігор",
    lastName: "Бондар",
    course: 2,
    avgScore: 73,
    major: "Право",
    hobbies: ["судові кейси", "читання"],
    hasDebts: true,
    group: "LW-04",
    startYear: 2025,
  },

  {
    firstName: "Наталія",
    lastName: "Ткаченко",
    course: 3,
    avgScore: 86,
    major: "Маркетинг",
    hobbies: ["SMM", "блогінг"],
    hasDebts: false,
    group: "MK-05",
    startYear: 2024,
  },
  {
    firstName: "Богдан",
    lastName: "Кравчук",
    course: 4,
    avgScore: 78,
    major: "ІТ",
    hobbies: ["DevOps", "читання"],
    hasDebts: false,
    group: "IT-01",
    startYear: 2023,
  },
  {
    firstName: "Дарина",
    lastName: "Мельник",
    course: 1,
    avgScore: 93,
    major: "Дизайн",
    hobbies: ["графіка", "малювання"],
    hasDebts: false,
    group: "DS-02",
    startYear: 2026,
  },
  {
    firstName: "Владислав",
    lastName: "Шевчук",
    course: 2,
    avgScore: 80,
    major: "Економіка",
    hobbies: ["бізнес", "аналітика"],
    hasDebts: false,
    group: "EC-03",
    startYear: 2025,
  },
  {
    firstName: "Олена",
    lastName: "Гриценко",
    course: 3,
    avgScore: 87,
    major: "Право",
    hobbies: ["дебати", "читання"],
    hasDebts: false,
    group: "LW-04",
    startYear: 2024,
  },
];






